### ISSUE TITLE
Some tile bricks are rotated 90ᵒ

### ISSUE THREAD

**Issue by Pardonreed** [brickadia/bls2brs#3]
Similar to how corner bricks incorrectly load, tiles load in the wrong orientation as well.
![image](https://user-images.githubusercontent.com/21185856/65823253-8d9c7400-e207-11e9-86a7-203c0b4822e7.png)

**Comment by qoh** [comment]
I believe this is not as simple as corner bricks: there may be multiple add-ons that add different shapes of tile bricks, and some of them name a W wide and L long tile `WxL Tile`, while others name them `LxW Tile`.

If this is the case, the proper fix to this would involve creating a dataset of all tile UI names together with their most common orientation. This requires gathering together all the tile add-ons that people use.

**Comment by qoh** [comment]
The proper fix to this would involve creating a dataset of all tile UI names together with their most common orientation. This requires gathering together all the tile add-ons that people use.
